---
- name: create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    state: present
  register: vpc

- name: set VPC ID in variable
  set_fact:
    vpc_id: "{{ vpc.vpc.id }}"

- name: associate subnet to the VPC
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    cidr: "{{ subnet_cidr1 }}"
    map_public: yes
  register: subnet1

- name: associate subnet to the VPC
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    cidr: "{{ subnet_cidr2 }}"
    map_public: yes
  register: subnet2

- name: associate subnet to the VPC
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    cidr: "{{ subnet_cidr3 }}"
    map_public: yes
  register: subnet3



- name: create IGW
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    state: "present"
    tags:
      Name: "{{ igw_name }}"
  register: igw

- name: Route IGW
  ec2_vpc_route_table:
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      subnets:
        - "{{ subnet1.subnet.id }}"
        - "{{ subnet2.subnet.id }}"
        - "{{ subnet3.subnet.id }}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{ igw.gateway_id  }}"
      tags:
        Name: "Route_Table"

- name: Create Security Group
  ec2_group:
      name: Web DMZ
      description: DMZ Security Group
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      rules:
        - proto: tcp
          ports:
            - 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
            - 443
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports:
            - 8080
          cidr_ip: 0.0.0.0/0
  register: security_group


- name: Create a Ec2 server
  ec2:
      assign_public_ip: "yes"
      image: ami-04b9e92b5572fa0d1
      instance_type : t2.small
      region : "{{ region }}"
      group_id: "{{ security_group.group_id }}"
      vpc_subnet_id: "{{ subnet1.subnet.id }}"
      keypair: "{{key_pair}}"
      exact_count: 1
      count_tag:
        app: jenkins
      instance_tags:
        app: jenkins
      wait: true
  register : Myec2

- name: Add A record for the new EC2 instance IP in Route53.
  route53:
    command: create
    zone: "{{route53_zone_name}}"
    record: "{{route53_record_name}}"
    type: A
    ttl: 60
    value: "{{ item.public_ip }}"
    wait: true
    overwrite: true
  with_items: '{{ Myec2.instances }}'

- name: Add new instance to host group
  add_host:
      hostname: "{{ item.public_ip }}"
      groupname: launched
      ansible_ssh_user: ubuntu
  loop: "{{ Myec2.instances }}"

- name: Let's wait for SSH to come up. Usually that takes ~10 seconds
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: '{{ Myec2.instances }}'

- name: Add new instance to host group
  add_host:
    groupname: launched
    hostname: "{{ item.public_ip }}"
    ansible_ssh_user: ubuntu
    host_key_checking: false
  loop: "{{ Myec2.instances }}"


- name: Let's wait for SSH to come up. Usually that takes ~10 seconds
  local_action: wait_for
    host={{ item.public_ip }}
    port=22
    state=started
  with_items: '{{ Myec2.instances }}'