---

- name: 'gather all the ec2 instance'
  ec2_instance_info:
    filters:
      {tag-key: "{{key}}", tag-value: "{{value}}"}
    region : "{{region}}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2



- name: 'Terminate EC2 Instance(s)'
  ec2:
    instance_ids: '{{ item.instance_id }}'
    state: absent
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    wait: true
  with_items: "{{ ec2.instances }}"







- ec2_vpc_net_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    filters:
      "tag:Name": MyVPC
  register: vpc

- name:               'Set VPC ID in variable'
  set_fact:
    vpc_id:           "{{ vpc.vpcs[0].vpc_id }}"


- name: 'Remove subnet1 from Vpc'
  ec2_vpc_subnet:
    state: absent
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ subnet_cidr1 }}"

- name: 'Remove subnet2 from Vpc'
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    state: absent
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ subnet_cidr2 }}"

- name: 'Remove subnet3 from Vpc'
  ec2_vpc_subnet:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    state: absent
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ subnet_cidr3 }}"


- ec2_vpc_route_table_info:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    filters:
      "tag:Name": "Route_Table"
  register: route




- name: "Delete security group by its id"
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    name: Web DMZ
    state: absent


- name : "Delete internet gateway"
  ec2_vpc_igw:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{region }}"
    vpc_id:  "{{ vpc_id }}"
    state: absent
  register: deligw

- name: delete route table
  ec2_vpc_route_table:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    vpc_id: "{{ vpc_id }}"
    region: "{{region }}"
    route_table_id: "{{ route.route_tables[0].id }}"
    lookup: id
    state: absent



- name: delete VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    state: absent
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
